### ISSUE TITLE
callback url

### ISSUE THREAD

**Issue by ggepenyan** [watanabeyu/react-native-simple-twitter#10]
When I enter my username and password, a pin code appears in the screen, and I'm told to copy it and return to the application to complete authorization process.
Iguess that it could be because of my callback url. It is empty in twitter application manager. I don't know what to do (((

**Comment by watanabeyu** [comment]
Hi @ggepenyan .
Are you entering callback on apps.twitter.com?
![2018-04-06 19 37 37](https://user-images.githubusercontent.com/6455904/38417128-1dbd2794-39d2-11e8-932e-4f7cfced051b.png)

Probably it is okay to set a callback url on apps.twitter.com.

**Comment by ggepenyan** [comment]
Sorry for late response. This was because of Twitter app configuration.
I used ready app, not created from scratch ))

**Comment by yogiw** [comment]
Hey what are you doing with this issue? I got this problem too.
