### ISSUE TITLE
Error 32 Could not authenticate you on account/verify_credentials.json

### ISSUE THREAD

**Issue by davebro** [watanabeyu/react-native-simple-twitter#15]
When calling the account/verify_credentials.json endpoint, it returns an error 32 "could not authenticate you". In looking through the code, I believe it is due to the generated signature. When I use postman to make the request using OAuth 1.0 and fill in the required parameters, it generates a different signature in the OAuth authorization header and is successful. Any ideas? Could it be due to the way the crypto-js library is handling it?

**Comment by watanabeyu** [comment]
Hi @davebro 

I'm sorry to be late.
What's your version?
The latest version is v1.2.4.

I found bug at v1.2.0, and fixed it already.

If you don't use v1.2.4, please use v.1.2.4

**Comment by EnesBildiren** [comment]
v.1.2.4 for what? Where will I use the v.1.2.4?

**Comment by watanabeyu** [comment]
Hi @EnesBildiren 
latest version is v2.0.0
If you want to use v1.2.4, please download below.

https://github.com/watanabeyu/react-native-simple-twitter/releases/tag/v1.2.4
