### ISSUE TITLE
react-navigation reset not working in onSuccess

### ISSUE THREAD

**Issue by shoichi1023** [watanabeyu/react-native-simple-twitter#20]
I wanna go component2 when I login successed.
but this code not working in onSuccess.
but this work in onPress.

```
const resetAction = NavigationActions.reset({
      index: 0,
      key: null,
      actions: [NavigationActions.navigate({ routeName: 'TabNavRoot' })],
    });
    this.props.navigation.dispatch(resetAction);
```
please teach me.
<br>
***my navigation***

StackNavigation
   - component1
   - TabNavRoot(TabNavigation)
           - component2
           - component3
           - component4

**Comment by shoichi1023** [comment]
`
/*not working*/
  onSuccess = (user) => {
    this.props.setUser(user);
    const resetAction = NavigationActions.reset({
      index: 0,
      key: null,
      actions: [NavigationActions.navigate({ routeName: 'TabNavRoot' })],
    });
    this.props.navigation.dispatch(resetAction);
  }
/*working*/
  onPress = ()=>{
    this.props.setUser({name:'aaaaaa'});
    const resetAction = NavigationActions.reset({
      index: 0,
      key: null,
      actions: [NavigationActions.navigate({ routeName: 'TabNavRoot' })],
    });
    this.props.navigation.dispatch(resetAction);
  }
`

**Comment by shoichi1023** [comment]
`
/*not working*/
 onSuccess = (user) => {
   this.props.setUser(user); 
   const resetAction = NavigationActions.reset({
       index: 0,
       key: null,
       actions: [NavigationActions.navigate({ routeName: 'TabNavRoot' })], 
   });
   this.props.navigation.dispatch(resetAction); 
 } 
/*working*/
 onPress = ()=>{ 
     this.props.setUser({name:'aaaaaa'});
     const resetAction = NavigationActions.reset({ 
       index: 0, 
       key: null,
       actions: [NavigationActions.navigate({ routeName: 'TabNavRoot' })], 
     });
     this.props.navigation.dispatch(resetAction); 
 }
`

**Comment by shoichi1023** [comment]
```
/*not working*/
  onSuccess = (user) => {
    this.props.setUser(user);
    const resetAction = NavigationActions.reset({
      index: 0,
      key: null,
      actions: [NavigationActions.navigate({ routeName: 'TabNavRoot' })],
    });
    this.props.navigation.dispatch(resetAction);
  }
/*working*/
  onPress = ()=>{
    this.props.setUser({name:'aaaaaa'});
    const resetAction = NavigationActions.reset({
      index: 0,
      key: null,
      actions: [NavigationActions.navigate({ routeName: 'TabNavRoot' })],
    });
    this.props.navigation.dispatch(resetAction);
  }

```

**Comment by watanabeyu** [comment]
@shoichi1023

もしよければソースコード全体を https://snack.expo.io に差し支えがない範囲で載せてもらえますか？
自分が使っている範囲ではonSuccessでNavigationActionsができるので。
使っているpackageやreact-nativeのバージョンなどの情報もあわせて欲しいです。

**Comment by shoichi1023** [comment]
https://snack.expo.io/@shoichi/login


{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "dependencies": {
    "expo": "^26.0.0",
    "native-base": "^2.4.5",
    "react": "16.3.0-alpha.1",
    "react-native": "^0.54.2",
    "react-native-elements": "^0.19.1",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-keyboard-aware-view": "0.0.14",
    "react-native-myparallax-scroll-view": "^0.19.0",
    "react-native-parallax-scroll-view": "^0.21.0",
    "react-native-parallax-view": "^2.0.6",
    "react-native-scrollable-tab-view": "^0.8.0",
    "react-native-scrollable-tab-view-universal": "^0.1.1",
    "react-native-simple-twitter": "^2.0.2",
    "react-native-tab-view": "0.0.78",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^1.5.11",
    "react-navigation-redux-helpers": "^1.0.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0"
  }
}

よろしくお願いいたします。

**Comment by watanabeyu** [comment]
@shoichi1023 
多分原因は`react-native-simple-twitter`ではなく、
箇所は特定しておりませんが@shoichi1023 さんのコード内にあるのではないかと思います。
こちらでpageNation.js内の`tabNav`を下記に変更し、
onSuccess時に`NavigationActions.reset()`を実行したところ遷移されました。

```
const tabNav = TabNavigator({
  Home: {
    screen: () => (
      <View><Text>ok</Text></View>
    )
  },
},{
  tabBarOptions: {
      inactiveTintColor: '#bbb',
      activeTintColor: '#000',
      showLabel: false,
    },
    initialRouteName: 'Home',
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
    swipeEnabled: true,
    lazy: false,
})
```
![output](https://user-images.githubusercontent.com/6455904/41769737-366414b4-764b-11e8-9947-e7996b0aa13e.gif)

申し訳ないですがこちらで対応できるのはここまでですね…

よろしくお願いいたします。

**Comment by shoichi1023** [comment]
恐れ入ります、ありがとうございます。
確認してみます。
