### ISSUE TITLE
An example of logging user in

### ISSUE THREAD

**Issue by lingxiao** [watanabeyu/react-native-simple-twitter#21]
can you provide an example of how to log the user in? In particular how to get a user's consumer key and consumer secret from the client side as seen here: https://github.com/watanabeyu/react-native-simple-twitter/blob/master/src/client.js#L22.   Your example seems to assume the user is already logged in.

**Comment by watanabeyu** [comment]
Hi @lingxiao 
please see example directory.
https://github.com/watanabeyu/react-native-simple-twitter/blob/master/example

step1
init react-native-simple-twitter at [App.js](https://github.com/watanabeyu/react-native-simple-twitter/blob/master/example/App.js).
```jsx
import twitter from 'react-native-simple-twitter'
twitter.setConsumerKey("twitter consumerKey","twitter consumerKeySecret")
```

step2
set TWLoginButton at [src/screens/LoginScreen.js](https://github.com/watanabeyu/react-native-simple-twitter/blob/master/example/src/screens/LoginScreen.js)
```jsx
import {TWLoginButton} from 'react-native-simple-twitter'

<TWLoginButton
  style={{ width: "100%", height: 60 }}
  type="TouchableOpacity"
  onPress={this.onPress}
  onGetAccessToken={this.onGetAccessToken}
  onSuccess={this.onSuccess}
  onClose={this.onClose}
  onError={this.onError}><Text style={{ textAlign: "center", color: "#fff" }}>Login</Text></TWLoginButton>
```

if logged in success, twitter object automatically set token and accessToken.
so if you want to use acessToken and anccessTokenSecret, it can be used after success.

step3
if you want to call api(ex: [POST] statuses/update), react-native-simple-twitter is automatically set accessToken and accessTokenSecret.
please see [src/screens/HomeScreen.js](https://github.com/watanabeyu/react-native-simple-twitter/blob/master/example/src/screens/HomeScreen.js#L35)
```jsx
import twitter from 'react-native-simple-twitter'
twitter.post("status/update.json",{...params}).then(response => {})
```
