### ISSUE TITLE
onGetAccessToken never called

### ISSUE THREAD

**Issue by ggepenyan** [watanabeyu/react-native-simple-twitter#9]
when I press login button webview appears, but there is a text which says that my accesstoken and secret kesys are invalid. And says to return from where I came.
Also, I can see that verify_credentials request int componentWillMount, responses error with code 32(could not authenticate). Idon't know what to do, please help.
I use Expo(create-react-native-app).

**Comment by watanabeyu** [comment]
Hi @ggepenyan 
Did you set the information on apps.twitter.com?
